// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmsKv_ufafGbpuk81P4kh4yyYJ2NwHHXw',
    appId: '1:605041819048:web:1834d4e83b7e43ff28319d',
    messagingSenderId: '605041819048',
    projectId: 'dealio-eg7',
    authDomain: 'dealio-eg7.firebaseapp.com',
    storageBucket: 'dealio-eg7.firebasestorage.app',
    measurementId: 'G-604DYYVK47',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH8t9nLO7vcff2KE57Csx5nFPweDU5o1U',
    appId: '1:605041819048:android:77996cc4f65b7e7e28319d',
    messagingSenderId: '605041819048',
    projectId: 'dealio-eg7',
    storageBucket: 'dealio-eg7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFcJoC95el7gHbfoqa6C6dG2MpjOdshMc',
    appId: '1:605041819048:ios:c1a38daf2908ebf228319d',
    messagingSenderId: '605041819048',
    projectId: 'dealio-eg7',
    storageBucket: 'dealio-eg7.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFcJoC95el7gHbfoqa6C6dG2MpjOdshMc',
    appId: '1:605041819048:ios:c1a38daf2908ebf228319d',
    messagingSenderId: '605041819048',
    projectId: 'dealio-eg7',
    storageBucket: 'dealio-eg7.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmsKv_ufafGbpuk81P4kh4yyYJ2NwHHXw',
    appId: '1:605041819048:web:de2e184f517f12b428319d',
    messagingSenderId: '605041819048',
    projectId: 'dealio-eg7',
    authDomain: 'dealio-eg7.firebaseapp.com',
    storageBucket: 'dealio-eg7.firebasestorage.app',
    measurementId: 'G-CZ0Y999PP1',
  );
}
