// egypt_geo_data.dart
// ─────────────────────────────────────────────────────────────────────────────
// Complete list of all 27 Egyptian governorates and their major cities /
// districts, suitable for use in dropdown selectors.
//
// Usage:
//   final govs = EgyptGeoData.governorates;          // List<String>
//   final cities = EgyptGeoData.citiesFor('Cairo');  // List<String>

class EgyptGeoData {
  EgyptGeoData._();

  // Ordered list of all Egyptian governorates (Arabic-English common names).
  static const List<String> governorates = [
    'Cairo',
    'Giza',
    'Alexandria',
    'Qalyubia',
    'Sharqia',
    'Dakahlia',
    'Gharbia',
    'Monufia',
    'Kafr El Sheikh',
    'Beheira',
    'Damietta',
    'Port Said',
    'Ismailia',
    'Suez',
    'North Sinai',
    'South Sinai',
    'Matrouh',
    'Faiyum',
    'Beni Suef',
    'Minya',
    'Asyut',
    'Sohag',
    'Qena',
    'Luxor',
    'Aswan',
    'Red Sea',
    'New Valley',
  ];

  /// Maps each governorate to its primary cities / districts.
  static const Map<String, List<String>> _cities = {
    'Cairo': [
      'Nasr City',
      'Heliopolis',
      'Maadi',
      'Zamalek',
      'Downtown Cairo',
      'Dokki',
      'Mohandessin',
      'Shubra',
      'Ain Shams',
      'Helwan',
      'New Cairo',
      '6th of October (Cairo Side)',
      'Badr City',
      'Shorouk City',
      'Obour City',
      'Madinaty',
      'El Rehab',
      'Mostorod',
      'El Matariya',
      'Rod El Farag',
      'Imbaba',
      'Boulaq',
      'Garden City',
      'Katameya',
      'Tagamoa',
    ],
    'Giza': [
      'Giza City',
      '6th of October City',
      'Sheikh Zayed City',
      'Haram',
      'Faisal',
      'Agouza',
      'Boulaq El Dakrour',
      'Bashteel',
      'Imbaba (Giza Side)',
      'Badrashin',
      'Hawamdeya',
      'Saff',
      'Atfih',
      'Dahshour',
      'Abu El Nomros',
    ],
    'Alexandria': [
      'Smouha',
      'Sidi Gaber',
      'Montaza',
      'Miami',
      'Agami',
      'Borg El Arab',
      'New Borg El Arab',
      'Raml Station',
      'Kafr El Dawwar (Alex Side)',
      'Mandara',
      'Stanley',
      'Gleem',
      'San Stefano',
      'Cleopatra',
      'Zizinia',
    ],
    'Qalyubia': [
      'Banha',
      'Shubra El Kheima',
      'Khosous',
      'Qalyub',
      'Obour City (Qalyubia Side)',
      'Shibin El Qanatir',
      'Qaha',
      'Tukh',
      'El Khanka',
      'Kafr Shukr',
    ],
    'Sharqia': [
      'Zagazig',
      'Belbeis',
      'Minya El Qamh',
      'Abu Hammad',
      'El Ibrahimia',
      'Faqous',
      'El Husseiniya',
      'Diarb Negm',
      'Kafr Saqr',
      'Hehya',
      'Mashtool El Souk',
    ],
    'Dakahlia': [
      'Mansoura',
      'Talkha',
      'Mit Ghamr',
      'Aga',
      'Bilqas',
      'Dikirnis',
      'El Sinbillawayn',
      'El Manzala',
      'Sherbin',
      'Mataria',
      'Gamasa',
    ],
    'Gharbia': [
      'Tanta',
      'El Mahalla El Kubra',
      'Kafr El Zayat',
      'Zifta',
      'El Santa',
      'Basyoun',
      'Samannoud',
    ],
    'Monufia': [
      'Shebin El Kom',
      'Sadat City',
      'Menouf',
      'Quesna',
      'Tala',
      'Birket El Sab',
      'El Bagor',
      'Ashmoun',
    ],
    'Kafr El Sheikh': [
      'Kafr El Sheikh City',
      'Desouk',
      'Fouwa',
      'El Hamool',
      'Metoubes',
      'Sidi Salem',
      'El Riyad',
      'Baltim',
      'Beala',
    ],
    'Beheira': [
      'Damanhour',
      'Kafr El Dawwar',
      'Rashid (Rosetta)',
      'Edku',
      'Abu El Matamir',
      'Hosh Eissa',
      'El Delengat',
      'Itay El Barud',
      'Wadi El Natroun',
    ],
    'Damietta': [
      'Damietta City',
      'New Damietta',
      'Faraskour',
      'El Zarqa',
      'Kafr El Battikh',
      'El Roda',
    ],
    'Port Said': [
      'Port Said City',
      'Port Fouad',
      'El Arab',
      'El Manakh',
      'El Zohour',
      'El Dawahi',
    ],
    'Ismailia': [
      'Ismailia City',
      'Fayed',
      'Qantara East',
      'Qantara West',
      'El Tal El Kabir',
      'Abu Sultan',
    ],
    'Suez': [
      'Suez City',
      'Ain Sokhna',
      'Attaqa',
      'El Arbaeen',
      'El Ganayen',
    ],
    'North Sinai': [
      'Arish',
      'Rafah',
      'Sheikh Zuweid',
      'Bir El Abd',
      'Hasna',
      'Nakhl',
    ],
    'South Sinai': [
      'Sharm El Sheikh',
      'Dahab',
      'Nuweiba',
      'Taba',
      'El Tor',
      'Saint Catherine',
      'Abu Zenima',
    ],
    'Matrouh': [
      'Marsa Matrouh',
      'El Alamein',
      'El Hamam',
      'Sidi Barrani',
      'Siwa',
      'Dabaa',
    ],
    'Faiyum': [
      'Faiyum City',
      'Tamiya',
      'Sennoris',
      'Yusuf El Seddiq',
      'Ibshway',
    ],
    'Beni Suef': [
      'Beni Suef City',
      'Nasser',
      'El Fashn',
      'Beba',
      'Sumusta El Waqf',
      'Ihnasia',
    ],
    'Minya': [
      'Minya City',
      'Abu Qurqas',
      'Beni Mazar',
      'Samalut',
      'Matay',
      'Mallawi',
      'Dairut',
      'Maghagha',
    ],
    'Asyut': [
      'Asyut City',
      'Dairut',
      'Sahel Selim',
      'Manfalut',
      'Qusiya',
      'Abnoub',
      'El Ghanaim',
      'El Badari',
      'Sodfa',
    ],
    'Sohag': [
      'Sohag City',
      'Akhmim',
      'Girga',
      'El Balyana',
      'El Maragha',
      'Dar El Salam',
      'Tahta',
      'Juhayna',
    ],
    'Qena': [
      'Qena City',
      'Nag Hammadi',
      'Luxor (Qena Side)',
      'Deshna',
      'Farshut',
      'Qous',
      'Abu Tesht',
      'El Waqf',
    ],
    'Luxor': [
      'Luxor City',
      'Karnak',
      'Esna',
      'El Tod',
      'Armant',
      'New Tiba',
    ],
    'Aswan': [
      'Aswan City',
      'Kom Ombo',
      'Edfu',
      'Daraw',
      'Nasr El Nuba',
      'Abu Simbel',
      'Toshka',
    ],
    'Red Sea': [
      'Hurghada',
      'Safaga',
      'El Quseir',
      'Marsa Alam', 
      'Ras Gharib',
      'Shalatin',
    ],
    'New Valley': [
      'Kharga',
      'Dakhla',
      'Farafra',
      'Bahariya',
      'Paris (El Wadi)',
    ],
  };

  // Returns the sorted list of cities for a given [governorate].
  // Falls back to an empty list if the governorate is not found.
  static List<String> citiesFor(String governorate) {
    final cities = _cities[governorate] ?? [];
    return List<String>.from(cities);
  }
}
